on:
  workflow-dispatch:
  push:

permissions:
  id-tokens: write

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::683827130946:role/github-action
          aws-region: us-east-2
